#!/usr/bin/env bash

if [[ $# -ne 1 ]]; then
    echo "Usage: $0 filename"
    echo "provided a valid file as an argument."
    exit 1
fi

file="$1"

if [[ ! -f "$file" ]]; then
    echo "Error: File '$file' not found."
    exit 1
fi

while IFS= read -r num; do
    read -ra factors <<< "$(factor "$num")"
    m_factor=${factors[1]}
    if [[ -n "$m_factor" ]]; then
        quotient=$((num / m_factor))
        echo "${num}=${quotient}*${m_factor}"
    else
        echo "Error: Fails factor $num"
    fi
done < "$file"
